### ISSUE TITLE
[BUG] On clicking rebond in overview page, a random large value gets displayed instead of unbonding amount

### ISSUE THREAD

**Issue by Lord-of-Codes** [yieldscan/yieldscan-frontend#122]
Address - 5FKaHKVpFgr2zHS2XrGuHNRV3a2LwxyhTUkTqNy2sB3J2D8d
Network - WND
https://www.loom.com/share/995ebcdf65d74ce69f1977a66335d1de

**Comment by sahilnanda1995** [comment]
@Lord-of-Codes are you working on this? 
I am planning to push a fix for this along with #123  incase you are not

**Comment by Lord-of-Codes** [comment]
@sahilnanda1995 no. i am not working on it.
