### ISSUE TITLE
[BUG] On switching networks estimated rewards are displayed wrong

### ISSUE THREAD

**Issue by sahilnanda1995** [yieldscan/yieldscan-frontend#77]
Debugging required:
Possible useEffect issue where we might have missed reseting a variable or missed an argument for the effect to take place

**Comment by Lord-of-Codes** [comment]
@sahilnanda1995 

Cannot replicate the bug. The estimated rewards are the same -

1. When I switch networks.
2. When I clear local storage and reload the page.

https://www.loom.com/share/562bb0b8d06a4442b7c4bc6dab2d6633
